// USERS
export const GET_DATA_USERS_PROCESS = 'GET_DATA_USERS_PROCESS,';
export const GET_DATA_USERS_SUCCESS = 'GET_DATA_USERS_SUCCESS,';
export const GET_DATA_USERS_FAILED = 'GET_DATA_USERS_FAILED';